# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDateTime, Qt
from pendaftaran import Registrasi
from absensi import Absensi


class Ui_MainWindow(QtWidgets.QDialog):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
       
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 60, 311, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 0, 10, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnDaftar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnDaftar.setBaseSize(QtCore.QSize(0, 0))
        self.btnDaftar.setObjectName("btnDaftar")
        self.btnDaftar.clicked.connect(self.pendaftaranWindow)
        self.gridLayout.addWidget(self.btnDaftar, 0, 0, 1, 1)
        self.btnAbsen = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnAbsen.setObjectName("btnAbsen")
        self.btnAbsen.clicked.connect(self.menuAbsen)
        self.gridLayout.addWidget(self.btnAbsen, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.timer = QtCore.QTimer(self)
        self.timer.setInterval(1000)
        self.timer.timeout.connect(self.showDatetime)
        self.timer.start()
       

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Attendance App"))
        self.btnDaftar.setText(_translate("MainWindow", "Pendaftaran"))
        self.btnAbsen.setText(_translate("MainWindow", "Absensi"))

    def showDatetime(self):
        self.statusbar.showMessage(QDateTime.currentDateTime().toString('dd/MM/yyyy, hh:mm:ss'))
        
    def pendaftaranWindow(self):
        self._new_window = Registrasi(self)
        self._new_window.show()
        self._new_window.startVideo("0")

    def menuAbsen(self):
        self.absenWindow = Absensi(self)
        self.absenWindow.show()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
