# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pendaftaran.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QDialog, QMessageBox
from PyQt5.QtCore import QTimer
from PyQt5.uic import loadUi
import cv2
import numpy as np
import face_recognition
import os
import pickle


class Registrasi(QDialog):
    def __init__(self, parent):
        super(Registrasi, self).__init__()
        loadUi("./pendaftaran.ui", self)
        self.image = None
        self.imcrop = None
        self.path = 'foto'
        self.btnSave.setEnabled(False)
        self.txtName.setEnabled(False)
        self.btnCapture.clicked.connect(self.captureImage)
        self.btnCancel.clicked.connect(self.cancelCapture)
        self.btnSave.clicked.connect(self.simpanGambar)
        """
        self.Dialog = QtWidgets.QDialog(parent)
        self.Dialog.setObjectName("Dialog")
        self.Dialog.resize(474, 379)
        self.gridLayout = QtWidgets.QGridLayout(self.Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.btnCapture = QtWidgets.QPushButton(self.Dialog)
        self.btnCapture.setObjectName("btnCapture")
        self.gridLayout.addWidget(self.btnCapture, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtName = QtWidgets.QLineEdit(self.Dialog)
        self.txtName.setObjectName("txtName")
        self.horizontalLayout.addWidget(self.txtName)
        self.btnSave = QtWidgets.QPushButton(self.Dialog)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.retranslateUi(self.Dialog)
        QtCore.QMetaObject.connectSlotsByName(self.Dialog)
        """

    def closeEvent(self, event):
        self.timer.stop()
        self.capture.release()
        print("dialog window ditutup...")

    def startVideo(self, cameraName):
        if len(cameraName) == 1:
        	self.capture = cv2.VideoCapture(int(cameraName))
        else:
        	self.capture = cv2.VideoCapture(cameraName)
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.updateFrame)
        self.timer.start(40)

    def updateFrame(self):
        ret, self.image = self.capture.read()
        self.displayImage(self.image,False, 1)

    def faceRec(self, frame,crop):
        imgS = cv2.resize(frame,(0,0),None,0.25,0.25)
        imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)
        facelocframe = face_recognition.face_locations(imgS)

        for faceloc in facelocframe:
            top, right, bottom, left = faceloc
            top, right, bottom, left = top*4, right*4, bottom*4, left*4
            if crop:
                scale = 100
                tempimg = frame
                frame = tempimg[top-scale:bottom+scale, left-scale:right+scale]
                #frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
                frame = np.require(frame, np.uint8, 'C')
            
            else:
                cv2.rectangle(frame,(faceloc[3]*4,faceloc[0]*4),(faceloc[1]*4,faceloc[2]*4),(0,255,0),2)

        return frame

    def displayImage(self, image, crop, window=1):
        image = cv2.resize(image, (640, 480))
        try:
            image = self.faceRec(image,crop)
            self.imcrop = image
        except Exception as e:
            print(e)
        
        qformat = QImage.Format_Indexed8
        if len(image.shape) == 3:
            if image.shape[2] == 4:
                qformat = QImage.Format_RGBA8888
            else:
                qformat = QImage.Format_RGB888
               
        outImage = QImage(image, image.shape[1], image.shape[0], image.strides[0], qformat)
        outImage = outImage.rgbSwapped()

        if window == 1:
            self.label.setPixmap(QPixmap.fromImage(outImage))
            self.label.setScaledContents(True)

    def captureImage(self):
        self.timer.stop()
        self.displayImage(self.image,True, 1)
        self.btnSave.setEnabled(True)
        self.txtName.setEnabled(True)

    def cancelCapture(self):
        self.startVideo("0")
    
    def simpanGambar(self):
        self.allface_data = {}
        self.imgS = cv2.cvtColor(self.imcrop, cv2.COLOR_BGR2RGB)
        self.facescurframe = face_recognition.face_locations(self.imgS)
        self.encodecurframe = face_recognition.face_encodings(self.imgS,self.facescurframe)[0]
        self.nama = self.txtName.text().upper()

        if os.path.exists('encoded_face.dat'):
            with open('encoded_face.dat','rb') as extfile:
                self.allface_data = pickle.load(extfile)
                self.face_name = list(self.allface_data.keys())
                self.face_encoding = np.array(list(self.allface_data.values()))
        else:
            self.face_name = []

        
        if self.nama not in self.face_name:
            cv2.imwrite(f'{self.path}/{self.nama}.png', self.imcrop)
            self.allface_data[self.nama]= self.encodecurframe
            with open('encoded_face.dat','wb') as f:
                pickle.dump(self.allface_data,f)
            print('Save Face data success')
        else:
            print('Nama sudah terdaftar !')
            self.msg = QMessageBox()
            self.msg.setIcon(QMessageBox.Warning)
            self.msg.setText("Nama "+ self.nama +" Sudah Terdaftar !")
            self.msg.setWindowTitle("Warning !")
            self.msg.setStandardButtons(QMessageBox.Ok)
            self.msg.buttonClicked.connect(self.cancelCapture)
            self.msg.exec_()




