# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pendaftaran.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QDialog, QMessageBox
from PyQt5.QtCore import QTimer
from PyQt5.uic import loadUi
import cv2
import numpy as np
import face_recognition
import os
import pickle
import psycopg2
from config import config


class Registrasi(QDialog):
    def __init__(self, parent):
        super(Registrasi, self).__init__()
        loadUi("./pendaftaran.ui", self)
        self.image = None
        self.imcrop = None
        self.path = 'foto'
        self.disableInput()
        self.btnCapture.clicked.connect(self.captureImage)
        self.btnCancel.clicked.connect(self.cancelCapture)
        self.btnSave.clicked.connect(self.simpanGambar)

    def disableInput(self):
        self.btnSave.setEnabled(False)
        self.txtName.setEnabled(False)
        self.txtName.clear()

    def closeEvent(self, event):
        self.timer.stop()
        self.capture.release()
        print("dialog window ditutup...")

    def startVideo(self, cameraName):
        if len(cameraName) == 1:
        	self.capture = cv2.VideoCapture(int(cameraName))
        else:
        	self.capture = cv2.VideoCapture(cameraName)
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.updateFrame)
        self.timer.start(40)

    def updateFrame(self):
        ret, self.image = self.capture.read()
        self.displayImage(self.image,False, 1)

    def faceRec(self, frame,crop):
        imgS = cv2.resize(frame,(0,0),None,0.25,0.25)
        imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)
        facelocframe = face_recognition.face_locations(imgS)

        for faceloc in facelocframe:
            top, right, bottom, left = faceloc
            top, right, bottom, left = top*4, right*4, bottom*4, left*4
            if crop:
                scale = 100
                tempimg = frame
                frame = tempimg[top-scale:bottom+scale, left-scale:right+scale]
                frame = np.require(frame, np.uint8, 'C')
            
            else:
                cv2.rectangle(frame,(faceloc[3]*4,faceloc[0]*4),(faceloc[1]*4,faceloc[2]*4),(0,255,0),2)

        return frame

    def displayImage(self, image, crop, window=1):
        image = cv2.resize(image, (640, 480))
        try:
            image = self.faceRec(image,crop)
            self.imcrop = image
        except Exception as e:
            print(e)
        
        qformat = QImage.Format_Indexed8
        if len(image.shape) == 3:
            if image.shape[2] == 4:
                qformat = QImage.Format_RGBA8888
            else:
                qformat = QImage.Format_RGB888
               
        outImage = QImage(image, image.shape[1], image.shape[0], image.strides[0], qformat)
        outImage = outImage.rgbSwapped()

        if window == 1:
            self.label.setPixmap(QPixmap.fromImage(outImage))
            self.label.setScaledContents(True)

    def captureImage(self):
        self.timer.stop()
        self.displayImage(self.image,True, 1)
        self.btnSave.setEnabled(True)
        self.txtName.setEnabled(True)

    def cancelCapture(self):
        self.disableInput()
        self.startVideo("0")
    
    def simpanGambar(self):
        self.allface_data = {}
        self.imgS = cv2.cvtColor(self.imcrop, cv2.COLOR_BGR2RGB)
        self.facescurframe = face_recognition.face_locations(self.imgS)
        self.encodecurframe = face_recognition.face_encodings(self.imgS,self.facescurframe)[0]
        if len(self.txtName.text()) > 0:
            self.nama = self.txtName.text().upper()
            """
            if os.path.exists('encoded_face.dat'):
                with open('encoded_face.dat','rb') as extfile:
                    self.allface_data = pickle.load(extfile)
                    self.face_name = list(self.allface_data.keys())
                    self.face_encoding = np.array(list(self.allface_data.values()))
            else:
                self.face_name = []
            """
            self.conn = None
            self.exists = 0
            try:
                self.params = config()
                self.conn = psycopg2.connect(**self.params)
                self.cur = self.conn.cursor()
                self.cur.execute("""SELECT * FROM tb_karyawan WHERE nama = %s""",(self.nama,))
                self.exists = self.cur.rowcount
                self.conn.commit()
                self.cur.close()
            except (Exception, psycopg2.DatabaseError) as error:
                print(error)
            finally:
                if self.conn is not None:
                    self.conn.close()
            
            if self.exists > 0:
                print('Nama sudah terdaftar !')
                self.msg = QMessageBox()
                self.msg.setIcon(QMessageBox.Warning)
                self.msg.setText("Nama "+ self.nama +" Sudah Terdaftar !")
                self.msg.setWindowTitle("Warning !")
                self.msg.setStandardButtons(QMessageBox.Ok)
                self.msg.buttonClicked.connect(self.cancelCapture)
                self.msg.exec_()
            else:
                cv2.imwrite(f'{self.path}/{self.nama}.png', self.imcrop)
                self.face_enc = pickle.dumps(self.encodecurframe)
                """
                self.allface_data[self.nama]= self.encodecurframe
                with open('encoded_face.dat','wb') as f:
                    pickle.dump(self.allface_data,f)
                """
                try:
                    self.params = config()
                    self.conn = psycopg2.connect(**self.params)
                    self.cur = self.conn.cursor()
                    self.cur.execute("""INSERT INTO tb_karyawan(nama, nik, face_data) VALUES(%s,%s,%s)""",(self.nama, '0029',self.face_enc))
                    self.conn.commit()
                    self.cur.close()
                except (Exception, psycopg2.DatabaseError) as error:
                    print(error)
                finally:
                    if self.conn is not None:
                        self.conn.close()
                print('Save Face data success')
                self.msg = QMessageBox()
                self.msg.setIcon(QMessageBox.Information)
                self.msg.setText("Nama "+ self.nama +" Berhasil disimpan")
                self.msg.setWindowTitle("Info !")
                self.msg.setStandardButtons(QMessageBox.Ok)
                self.msg.buttonClicked.connect(self.cancelCapture)
                self.msg.exec_()
                
        else:
            self.msg = QMessageBox()
            self.msg.setIcon(QMessageBox.Warning)
            self.msg.setText("Nama belum diisi !")
            self.msg.setWindowTitle("Warning !")
            self.msg.setStandardButtons(QMessageBox.Ok)
            self.msg.exec_()
            




